on:
  push:
    branches:
      - master
    paths:
      - 'package.json'


name: Build

jobs:
  release:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: out/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: ${{ env.RELEASE_NAME }}
          body: |
            This is the auto-release of version ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: true


get_version:
  runs-on: ubuntu-latest
  outputs:
    version: ${{ steps.set_version.outputs.version }}
  steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
      
    - name: Set Package Version
      id: set_version
      run: |
        version=$(jq -r '.version' package.json)
        echo "VERSION=${version}" >> $GITHUB_ENV
        echo "RELEASE_NAME=${release_name}" >> $GITHUB_ENV
