name: Trigger Build

on:
  workflow_dispatch:

jobs:
  run_build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: GabouleDev/ModdedLauncher
          workflow: build.yml
          event-type: run-workflow

